
// Code generated by stanc v2.29.2
#include <stan/model/model_header.hpp>
namespace exponential_growth_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 26> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 11, column 4 to column 20)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 12, column 4 to column 22)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 13, column 4 to column 26)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 17, column 4 to column 29)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 18, column 4 to column 29)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 19, column 4 to column 19)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 21, column 8 to column 43)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 20, column 4 to line 21, column 43)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 32, column 3 to column 23)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 34, column 6 to column 45)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 33, column 3 to line 34, column 45)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 25, column 4 to column 36)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 26, column 4 to column 27)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 27, column 4 to column 31)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 28, column 4 to column 30)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 2, column 4 to column 10)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 3, column 11 to column 12)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 3, column 4 to column 16)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 4, column 11 to column 12)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 4, column 4 to column 16)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 6, column 4 to column 14)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 7, column 11 to column 16)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 7, column 4 to column 24)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 19, column 11 to column 12)",
 " (in '/Users/tomroeschinger/git/resistance_evolution/processing/plate_reader/20220701_r4_MG1655_calibration/stan/exponential_growth.stan', line 32, column 10 to column 15)"};




class exponential_growth_model final : public model_base_crtp<exponential_growth_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> t__;
  Eigen::Matrix<double, -1, 1> y__;
  int N_ppc;
  Eigen::Matrix<double, -1, 1> t_ppc__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> t{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> t_ppc{nullptr, 0};
 
 public:
  ~exponential_growth_model() { }
  
  inline std::string model_name() const final { return "exponential_growth_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.2", "stancflags = "};
  }
  
  
  exponential_growth_model(stan::io::var_context& context__,
                           unsigned int random_seed__ = 0,
                           std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "exponential_growth_model_namespace::exponential_growth_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 17;
      stan::math::validate_non_negative_index("t", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","t","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      t__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&t) Eigen::Map<Eigen::Matrix<double, -1, 1>>(t__.data(), N);
      
      {
        std::vector<local_scalar_t__> t_flat__;
        current_statement__ = 18;
        t_flat__ = context__.vals_r("t");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(t, t_flat__[(pos__ - 1)],
            "assigning variable t", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      y__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(y__.data(), N);
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 20;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      context__.validate_dims("data initialization","N_ppc","int",
           std::vector<size_t>{});
      N_ppc = std::numeric_limits<int>::min();
      
      
      current_statement__ = 21;
      N_ppc = context__.vals_i("N_ppc")[(1 - 1)];
      current_statement__ = 22;
      stan::math::validate_non_negative_index("t_ppc", "N_ppc", N_ppc);
      current_statement__ = 23;
      context__.validate_dims("data initialization","t_ppc","double",
           std::vector<size_t>{static_cast<size_t>(N_ppc)});
      t_ppc__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N_ppc,
          std::numeric_limits<double>::quiet_NaN());
      new (&t_ppc) Eigen::Map<Eigen::Matrix<double, -1, 1>>(t_ppc__.data(), N_ppc);
        
      
      {
        std::vector<local_scalar_t__> t_ppc_flat__;
        current_statement__ = 23;
        t_ppc_flat__ = context__.vals_r("t_ppc");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= N_ppc; ++sym1__) {
          current_statement__ = 23;
          stan::model::assign(t_ppc, t_ppc_flat__[(pos__ - 1)],
            "assigning variable t_ppc", stan::model::index_uni(sym1__));
          current_statement__ = 23;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 24;
      stan::math::validate_non_negative_index("y_th", "N", N);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("y_ppc", "N_ppc", N_ppc);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "exponential_growth_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ log_10_tau = DUMMY_VAR__;
      current_statement__ = 1;
      log_10_tau = in__.template read<local_scalar_t__>();
      local_scalar_t__ y_0 = DUMMY_VAR__;
      current_statement__ = 2;
      y_0 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ sigma_0 = DUMMY_VAR__;
      current_statement__ = 3;
      sigma_0 = in__.template read_constrain_lb<local_scalar_t__, 
                  jacobian__>(0, lp__);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 4;
      tau = stan::math::pow(10, log_10_tau);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 5;
      lambda = (stan::math::log(2) / tau);
      Eigen::Matrix<local_scalar_t__, -1, 1> y_th =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 8;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 7;
        stan::model::assign(y_th,
          (stan::math::log(y_0) +
            (lambda * stan::model::rvalue(t, "t", stan::model::index_uni(i)))),
          "assigning variable y_th", stan::model::index_uni(i));
      }
      {
        current_statement__ = 12;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(log_10_tau, 1.75, 0.25));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y_0, 0, 0.025));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_0, 0, 0.001));
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y, y_th, sigma_0));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "exponential_growth_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double log_10_tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      log_10_tau = in__.template read<local_scalar_t__>();
      double y_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      y_0 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double sigma_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      sigma_0 = in__.template read_constrain_lb<local_scalar_t__, 
                  jacobian__>(0, lp__);
      double tau = std::numeric_limits<double>::quiet_NaN();
      double lambda = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double, -1, 1> y_th =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      out__.write(log_10_tau);
      out__.write(y_0);
      out__.write(sigma_0);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 4;
      tau = stan::math::pow(10, log_10_tau);
      current_statement__ = 5;
      lambda = (stan::math::log(2) / tau);
      current_statement__ = 8;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 7;
        stan::model::assign(y_th,
          (stan::math::log(y_0) +
            (lambda * stan::model::rvalue(t, "t", stan::model::index_uni(i)))),
          "assigning variable y_th", stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(tau);
        out__.write(lambda);
        out__.write(y_th);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> y_ppc =
         Eigen::Matrix<double, -1, 1>::Constant(N_ppc,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 11;
      for (int i = 1; i <= N_ppc; ++i) {
        current_statement__ = 10;
        stan::model::assign(y_ppc,
          (stan::math::log(y_0) +
            (lambda *
              stan::model::rvalue(t_ppc, "t_ppc", stan::model::index_uni(i)))),
          "assigning variable y_ppc", stan::model::index_uni(i));
      }
      out__.write(y_ppc);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ log_10_tau = DUMMY_VAR__;
      log_10_tau = in__.read<local_scalar_t__>();
      out__.write(log_10_tau);
      local_scalar_t__ y_0 = DUMMY_VAR__;
      y_0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, y_0);
      local_scalar_t__ sigma_0 = DUMMY_VAR__;
      sigma_0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"log_10_tau", "y_0", "sigma_0", "tau",
      "lambda", "y_th", "y_ppc"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N_ppc)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "log_10_tau");
    param_names__.emplace_back(std::string() + "y_0");
    param_names__.emplace_back(std::string() + "sigma_0");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "tau");
      param_names__.emplace_back(std::string() + "lambda");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_th" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_ppc; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_ppc" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "log_10_tau");
    param_names__.emplace_back(std::string() + "y_0");
    param_names__.emplace_back(std::string() + "sigma_0");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "tau");
      param_names__.emplace_back(std::string() + "lambda");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_th" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_ppc; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_ppc" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"log_10_tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"y_th\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_ppc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_ppc) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"log_10_tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"y_th\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"y_ppc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_ppc) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = ((1 + 1) + N);
      const size_t num_gen_quantities = N_ppc;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = ((1 + 1) + N);
      const size_t num_gen_quantities = N_ppc;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"log_10_tau", "y_0",
      "sigma_0"};
      const std::array<Eigen::Index, 3> constrain_param_sizes__{1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = exponential_growth_model_namespace::exponential_growth_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return exponential_growth_model_namespace::profiles__;
}

#endif


